API endpoints for DNS DHCP & FTLdb
pi-hole/api pull request #42
Opened 2018-06-27 00:24 UTC by rrobgill

Additional endpoints under /settings

FTLdb using data from the FTL api
DNS and DHCP data read from setupVars.conf

Signed-off-by: Rob Gill <rrobgill@protonmail.com>

2018-06-27 01:09 UTC, AzureMarker requested changes

2018-06-27 13:59 UTC, AzureMarker requested changes

2018-06-28 00:12 UTC, AzureMarker requested changes

2018-06-28 02:42 UTC, AzureMarker requested changes

2018-06-28 22:38 UTC, AzureMarker requested changes

2018-06-29 12:43 UTC, AzureMarker requested changes

2018-06-29 15:15 UTC, AzureMarker requested changes

2018-06-30 08:27 UTC, rrobgill reviewed
Good stuff. Does just what it says. 

test result: ok. 57 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

2018-06-30 19:36 UTC, AzureMarker requested changes

2018-07-01 01:18 UTC, AzureMarker requested changes

2018-07-01 03:22 UTC, AzureMarker requested changes

2018-07-01 15:07 UTC, AzureMarker approved these changes

2018-07-01 15:17 UTC, merged